[package]
name = "swarm-test"
version = "0.1.0"
authors = ["mgr-inz-rafal <rchabowski@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "*"
piston-gfx_texture = "*"
gfx_device_gl = "0.15.0"
gfx = "0.17.1"
piston2d-gfx_graphics = "*"
swarm = { path = "../swarm" }
